# Generated by Django 6.0.3 on 2026-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magnolia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('stellata', 'Magnolia stellata (Star Magnolia)'), ('soulangeana', 'Magnolia × soulangeana (Saucer Magnolia)'), ('grandiflora', 'Magnolia grandiflora (Southern Magnolia)'), ('liliiflora', 'Magnolia liliiflora (Lily Magnolia)'), ('kobus', 'Magnolia kobus'), ('other', 'Other / Unknown')], default='other', max_length=50)),
                ('location_description', models.CharField(help_text='e.g. Campbell Park, Central Milton Keynes', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Decimal latitude (e.g. 52.041)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Decimal longitude (e.g. -0.759)', max_digits=9, null=True)),
                ('date_observed', models.DateField(help_text='Date the magnolia was observed')),
                ('blooming_status', models.CharField(choices=[('budding', 'Budding'), ('blooming', 'Blooming'), ('past_bloom', 'Past Bloom'), ('dormant', 'Dormant')], default='dormant', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='magnolias/')),
                ('logged_by', models.CharField(blank=True, max_length=100)),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magnolia',
                'verbose_name_plural': 'Magnolias',
                'ordering': ['-date_observed', '-date_logged'],
            },
        ),
    ]
